version: "3.5"

services:

  bastion:
    build:
      context: "."
      args:
        VERSION: "test"
    ports:
      - "8888:22"
    volumes:
      - "$HOME/.ssh/id_rsa.pub:/authorized_keys"
    environment:
      LOG_LEVEL: "DEBUG"
