services:

  bastion:
    build:
      context: "."
      args:
        VERSION: "test"
    volumes:
      - "./test/ida_rsa.pub:/authorized_keys"
      - "./test/google_authenticator:/.google_authenticator"
    environment:
      LOG_LEVEL: "DEBUG"

  test:
    build: "./test"
    volumes:
      - "./test/ida_rsa:/root/.ssh/id_rsa"
      - "./test/google_authenticator_code:/code"
      - "./test/test.sh:/test.sh"
    command: "/test.sh"
    depends_on:
      - "bastion"
