name: ci

on:
  push:
    branches:
      - master
    tags:
      - '*.*.*'

  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      REPO: neochrome/bastion

    steps:

      - name: Build args
        id: build-args
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION="${GITHUB_REF#refs/tags/}"
            if [[ $VERSION =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
              MAJOR="${BASH_REMATCH[1]}"
              MINOR="${BASH_REMATCH[2]}"
              PATCH="${BASH_REMATCH[3]}"
              TAGS="${REPO}:latest"
              TAGS="${TAGS},${REPO}:${MAJOR}"
              TAGS="${TAGS},${REPO}:${MAJOR}.${MINOR}"
              TAGS="${TAGS},${REPO}:${MAJOR}.${MINOR}.${PATCH}"
            fi
          elif [[ $GITHUB_REF == refs/heads/* ]]; then
            VERSION=dev
            TAGS="${REPO}:${VERSION}"
          fi
          echo "::set-output name=version::${VERSION}"
          echo "::set-output name=tags::${TAGS}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        if: ${{ !env.ACT && github.event_name != 'pull_request' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v7
            linux/arm/v6
          push: ${{ !env.ACT && github.event_name != 'pull_request' }}
          tags: ${{ steps.build-args.outputs.tags }}
          build-args: |
            VERSION=${{ steps.build-args.outputs.version }}
